package com.kalaazu.server.game.commands;

import com.kalaazu.KalaazuConfig;
import com.kalaazu.model.Version;
import jakarta.annotation.PostConstruct;
import lombok.RequiredArgsConstructor;
import org.springframework.context.ApplicationContext;
import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * A factory class for building game commands.
 *
 * This component scans the application context for all available `CommandBuilderInterface`
 * implementations and organizes them by game version and command type. It provides a
 * centralized way to construct game commands based on the application's current
 * configuration, abstracting the specific command creation logic away from the systems
 * that need them.
 *
 * @example
 * ```java
 * // This class is managed by Spring and typically injected.
 * // In a game system:
 *
 * @Autowired
 * private CommandBuilder commandBuilder;
 *
 * public void sendEntityCreation(int entityId) {
 *     // Build all commands related to entity creation for a specific entity
 *     List<OutCommand> commands = commandBuilder.buildCommands(
 *         CommandType.EntityCreationCommand,
 *         world, // com.artemis.World instance
 *         entityId
 *     );
 *
 *     // ... then send the commands to the client.
 * }
 * ```
 *
 * @see com.kalaazu.server.game.commands.CommandBuilderInterface
 * @see com.kalaazu.server.game.commands.CommandType
 * @see com.kalaazu.server.game.commands.OutCommand
 *
 * @author manulaiko <manulaiko@gmail.com>
 */
@Component
@RequiredArgsConstructor
public class CommandBuilder {
    private final ApplicationContext context;
    private final KalaazuConfig config;
    private Map<Version, Map<CommandType, List<CommandBuilderInterface>>> builders;

    /**
     * Initializes the command builder by scanning for and organizing all command builder beans.
     *
     * This method is invoked by the Spring container after the bean has been constructed.
     * It finds all beans of type `CommandBuilderInterface` in the application context and
     * groups them into a nested map. The first level of grouping is by the game `Version`
     * they support, and the second level is by the `CommandType` they build. This
     * pre-computation allows for efficient command creation later on.
     *
     * @example ```java
     * // This method is a lifecycle callback managed by the Spring framework
     * // and should not be called directly.
     * ```
     * @see jakarta.annotation.PostConstruct
     * @see com.kalaazu.server.game.commands.CommandBuilderInterface
     */
    @PostConstruct
    public void init() {
        builders = context.getBeansOfType(CommandBuilderInterface.class)
                .values()
                .stream()
                .collect(Collectors.groupingBy(
                        CommandBuilderInterface::getGameVersion,                 // first level: Version
                        Collectors.groupingBy(CommandBuilderInterface::getCommandType) // second level: CommandType
                ));
    }

    /**
     * Builds a list of `OutCommand`s for a specific command type and arguments.
     *
     * This method looks up the appropriate builders for the game version specified in the
     * application configuration and the given `CommandType`. It then invokes each of
     * these builders with the provided arguments to generate the corresponding commands.
     *
     * @param type The type of command to build (e.g., `EntityCreationCommand`).
     * @param arguments The variable arguments to pass to the underlying builder implementations.
     *                  The required arguments depend on the specific command type.
     *
     * @return A list of all `OutCommand` instances generated by the relevant builders.
     *         Returns an empty list if no builders are found for the given type.
     *
     * @example
     * ```java
     * // Assuming 'commandBuilder' is an injected instance, 'world' is an Artemis World,
     * // and 'entityId' is the ID of an entity.
     * List<OutCommand> commands = commandBuilder.buildCommands(
     *     CommandType.EntityCreationCommand,
     *     world,
     *     entityId
     * );
     * ```
     */
    public List<OutCommand> buildCommands(CommandType type, Object... arguments) {
        var cmds = new ArrayList<OutCommand>();

        builders.get(config.getGame().getVersion())
                .getOrDefault(type, Collections.emptyList())
                .forEach(b -> cmds.addAll(b.build(arguments)));

        return cmds;
    }
}
